### ISSUE TITLE
In Android the images can not be displayed

### ISSUE THREAD

**Issue by snuzi** [ElNinjaGaiden/Gorillagram#6]
I ran the app in Android but the images are blank. Posts are shown correctly. Is this an issue for Android or something related to Cloudinary

**Comment by ElNinjaGaiden** [comment]
They should display fine. Do you see any error in the debug console?
You could try grabbing the url the app generates before to pull the images.

Let me know if you know how to change the code to do that or I can create a branch with that change.

**Comment by snuzi** [comment]
I didn't debug it, I'm not familiar with your code yet, to make the appropriate changes on it.

**Comment by ElNinjaGaiden** [comment]
I just created a branch called `print-image-urls`. The idea is to use that branch and run the app on your android device (with the device connected via USB to the computer).

With the device connect you will be able to open debug options by shaking your device (again, the device needs to be connected to the computer in order to make this work)

After shake your device, you will be prompted with a menu, choose "Debug JS Remotely". This action will open Chrome and you will be able to see the url's the app is trying to use in order to pull images from Cloudinary. Once you see the url's what you can do is copy them and trying directly on the browser.... or even see of you are getting any error before to generate the url's.

Let me know how that goes.

**Comment by snuzi** [comment]
I have some knowledge about debugging in React Native. I will try that a bit later and I'll let you know about it.
Have you tested the app in Android recently?

**Comment by ElNinjaGaiden** [comment]
Yes, last night I tried it on two different devices:

- LG Nexus 5 running Android 6.0.1

- Moto G (4th generation) running Android 7.0

**Comment by ElNinjaGaiden** [comment]
Ok, the problem was because we were using the current device width before to compose the url's we will be requesting to Cloudinary later. It seems in some devices the result of `Dimensions.get('window').width` could be a float value so we need to parse it to an intenter (no decimal) because Cloudinary doesn't accept decimals in measures parameters.

The fix was included in this [commit](https://github.com/ElNinjaGaiden/Gorillagram/commit/7eb67df76e16a19802ab3812de3a685999605c51)
